# the services part
services:
#mariadb
  mariadb:
    container_name: mariadb
    image: mariadb
    build: 
      context: requirements/mariadb
    volumes:
     - mariadb:/var/lib/mysql
    env_file: .env
    networks:
     - inception
    restart: unless-stopped
    expose:
     - "3306:3306"
    healthcheck:
      test: test -f /tmp/started
      interval: 5s
      timeout: 1s
      retries: 30
      start_period: 5s


#nginx
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: requirements/nginx
    env_file: .env
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: on-failure
    #healthcheck:
    #  test: test -f /tmp/started
    #  interval: 5s
    #  timeout: 1s
    #  retries: 30
    #  start_period: 5s


#wordpress
  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    env_file: .env
    expose:
      - "9000"
    networks:
      - inception
    restart: on-failure
    healthcheck:
      test: test -f /tmp/started
      interval: 5s
      timeout: 1s
      retries: 30
      start_period: 5s

# the volumes part
volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /Users/momox/Documents/42/volumes/data/mariadb
      o : bind
      type : none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /Users/momox/Documents/42/volumes/data/wordpress
      o : bind
      type : none

# the networks part
networks:
  inception:
    driver: bridge